packages:
- packages/*
- tooling/*
- apps/*

catalog:
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^4.1.11
  typescript: ^5.9.2

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.2
