name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3
  HUSKY: 0

jobs:
  build:
    name: ⚒️ Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup
      - run: pnpm build --filter="./packages/*"

  operation-catalogs:
    name: 📚 Operation Catalogs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup
      - run: pnpm --filter @quranjs/api check:operation-catalogs

  lint:
    name: ✨ Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup
      - run: pnpm lint --quiet

  typecheck:
    name: 🔍 Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup
      - run: pnpm typecheck

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup
      - run: pnpm test
