name: PR

on: [pull_request]

env:
  HUSKY: 0

jobs:
  build:
    name: ⚒️ Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x', '20.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
  
      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Lint
        run: pnpm lint --quiet

      - name: Test
        run: pnpm test:coverage

      - name: Build
        run: pnpm build

  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
